-- Clear existing sample airline data (optional - remove this if you want to keep the original 8)
DELETE FROM public.logo_items WHERE category = 'airline';

-- Insert top 50 airlines with corrected schema
INSERT INTO public.logo_items (category, name, logo_image_url, is_active) VALUES
('airline', 'Emirates', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Emirates_logo.svg/320px-Emirates_logo.svg.png', true),
('airline', 'Singapore Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Singapore_Airlines_logo.svg/320px-Singapore_Airlines_logo.svg.png', true),
('airline', 'Lufthansa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Lufthansa_logo.svg/320px-Lufthansa_logo.svg.png', true),
('airline', 'IndiGo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/IndiGo_Logo.svg/320px-IndiGo_Logo.svg.png', true),
('airline', 'Air India', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Air_India_Logo.svg/320px-Air_India_Logo.svg.png', true),
('airline', 'SpiceJet', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/SpiceJet_Logo.svg/320px-SpiceJet_Logo.svg.png', true),
('airline', 'Akasa Airways', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Akasa_Airways_logo.svg/320px-Akasa_Airways_logo.svg.png', true),
('airline', 'United Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/United_Airlines_logo_2018.svg/320px-United_Airlines_logo_2018.svg.png', true),
('airline', 'Qatar Airways', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Qatar_Airways_Logo.svg/320px-Qatar_Airways_Logo.svg.png', true),
('airline', 'Cathay Pacific', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Cathay_Pacific_logo.svg/320px-Cathay_Pacific_logo.svg.png', true),
('airline', 'Qantas', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Qantas_Logo.svg/320px-Qantas_Logo.svg.png', true),
('airline', 'Delta Air Lines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Delta_Air_Lines_logo.svg/320px-Delta_Air_Lines_logo.svg.png', true),
('airline', 'American Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/American_Airlines_logo_2013.svg/320px-American_Airlines_logo_2013.svg.png', true),
('airline', 'British Airways', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/British_Airways_logo.svg/320px-British_Airways_logo.svg.png', true),
('airline', 'KLM', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/KLM_logo.svg/320px-KLM_logo.svg.png', true),
('airline', 'Air France', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Air_France_logo.svg/320px-Air_France_logo.svg.png', true),
('airline', 'Etihad Airways', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Etihad_Airways_logo.svg/320px-Etihad_Airways_logo.svg.png', true),
('airline', 'Iberia', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Iberia_Logo.svg/320px-Iberia_Logo.svg.png', true),
('airline', 'Air Canada', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Air_Canada_Logo.svg/320px-Air_Canada_Logo.svg.png', true),
('airline', 'Japan Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Japan_Airlines_logo.svg/320px-Japan_Airlines_logo.svg.png', true),
('airline', 'Korean Air', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Korean_Air_logo.svg/320px-Korean_Air_logo.svg.png', true),
('airline', 'Asiana Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Asiana_Airlines_logo.svg/320px-Asiana_Airlines_logo.svg.png', true),
('airline', 'Garuda Indonesia', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Garuda_Indonesia_logo.svg/320px-Garuda_Indonesia_logo.svg.png', true),
('airline', 'Emirates SkyCargo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Emirates_SkyCargo_logo.svg/320px-Emirates_SkyCargo_logo.svg.png', true),
('airline', 'Alaska Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Alaska_Airlines_logo.svg/320px-Alaska_Airlines_logo.svg.png', true),
('airline', 'Southwest Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Southwest_Airlines_logo.svg/320px-Southwest_Airlines_logo.svg.png', true),
('airline', 'Ryanair', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Ryanair_logo.svg/320px-Ryanair_logo.svg.png', true),
('airline', 'easyJet', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/EasyJet_logo.svg/320px-EasyJet_logo.svg.png', true),
('airline', 'Aeroflot', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Aeroflot_logo.svg/320px-Aeroflot_logo.svg.png', true),
('airline', 'Alitalia', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Alitalia_Logo.svg/320px-Alitalia_Logo.svg.png', true),
('airline', 'China Southern Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/China_Southern_Airlines_logo.svg/320px-China_Southern_Airlines_logo.svg.png', true),
('airline', 'China Eastern Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/China_Eastern_Air_Line_logo.svg/320px-China_Eastern_Air_Line_logo.svg.png', true),
('airline', 'Hainan Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hainan_Airlines_logo.svg/320px-Hainan_Airlines_logo.svg.png', true),
('airline', 'Vietnam Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Vietnam_Airlines_logo.svg/320px-Vietnam_Airlines_logo.svg.png', true),
('airline', 'TAP Air Portugal', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/TAP_Air_Portugal_logo.svg/320px-TAP_Air_Portugal_logo.svg.png', true),
('airline', 'SAS (Scandinavian Airlines)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/SAS_Logo.svg/320px-SAS_Logo.svg.png', true),
('airline', 'Swiss International Air Lines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Swiss_International_Air_Lines_logo.svg/320px-Swiss_International_Air_Lines_logo.svg.png', true),
('airline', 'Turkish Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Turkish_Airlines_Logo.svg/320px-Turkish_Airlines_Logo.svg.png', true),
('airline', 'Virgin Atlantic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Virgin_Atlantic_logo.svg/320px-Virgin_Atlantic_logo.svg.png', true),
('airline', 'QantasLink', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/QantasLink_logo.svg/320px-QantasLink_logo.svg.png', true),
('airline', 'Scoot', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Scoot_logo.svg/320px-Scoot_logo.svg.png', true),
('airline', 'Jet Airways', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Jet_Airways_Logo.svg/320px-Jet_Airways_Logo.svg.png', true),
('airline', 'AirAsia', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/AirAsia_logo.svg/320px-AirAsia_logo.svg.png', true),
('airline', 'SriLankan Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/SriLankan_Airlines_logo.svg/320px-SriLankan_Airlines_logo.svg.png', true),
('airline', 'Oman Air', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Oman_Air_logo.svg/320px-Oman_Air_logo.svg.png', true),
('airline', 'Royal Air Maroc', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Royal_Air_Maroc_logo.svg/320px-Royal_Air_Maroc_logo.svg.png', true),
('airline', 'El Al', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/El_Al_logo.svg/320px-El_Al_logo.svg.png', true),
('airline', 'Aerolineas Argentinas', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Aerolineas_Argentinas_logo.svg/320px-Aerolineas_Argentinas_logo.svg.png', true),
('airline', 'Philippine Airlines', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Philippine_Airlines_logo.svg/320px-Philippine_Airlines_logo.svg.png', true),
('airline', 'Cathay Pacific Cargo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Cathay_Pacific_logo.svg/320px-Cathay_Pacific_logo.svg.png', true);